{% set name = "aws-sigv4" %}
{% set version = "1.1.3" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 4de726404f8f1c7808d9f0805e51a47d96001bd3b613c9ea7a6fcf1fb8efda4f

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby
    - rb-aws-eventstream >=1.0.2,<2

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Amazon Web Services Signature Version 4 signing ligrary. Generates sigv4 signature for HTTP requests.

  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/aws/aws-sdk-ruby

extra:
  recipe-maintainers:
    - conda-forge/ruby
    - pierrsc
