travis:
  secure:
    BINSTAR_TOKEN: FFRxId3IySF4snD1JNDEvYLtLaHZsmE2sAN1ePP/ijhPUz7CpCwhgPOExCsp19qyb+T794jSY9kAIrTKBtpAKI+J6rtpjYcP5+fMXhcWZ1j8JK0I+cr/jWGEt5g6KXWdyelNsoMF/eQwrJmw9uGJ2cNOepMw8Q7toQDOLvmXqw8jeb04JTYoPxXHOtYWxzGpudnYanllaHdaarhiRnAENKgSKT8ezJ+gKNpZWu5hSBp8xHhaFI4+TeLo2bsbEWB0KT1/TNGGgKIZA9EZeRAm7Ida88nzNHpz/AkrontvvD7hzEr37RWHEMn8LQrtAsoxKKW1iovM2nyb6jkpi0petFlThMXQtW9fCOzkTufKwRb46e+5cMnC16b6hN7bJmf7mP4gqELKQoGDt0PUKh1qo+9qdjXzZOUxZexixIgmd5BlWMn6pfzUgrhHa3LhkSeYwwf7f4941egIVK9WsWWbAWa6MOuODwOr9Yokodyig5FF6YOuHJSriGallIB8YLxjQQq/z6qWofuw/zAGBOCueyeh+an8tW2Lk+Hmg3zaMQmcxnEilJLA23GQ37/SJsgr0StOIBg9A2iLQv1OfWP5pu9yDiVptqICeH1q9fmCmftik8Wt+R6P2xvNd3qQuH4Jew3Rh1buMm09jGU5Z8SCrEHQOGdPv/ptZsuKoDFuQVg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
