travis:
  secure:
    BINSTAR_TOKEN: 3YzsIo8RHloYsFytxqE78Go6GoSzkpnyV0buoZ3l/B/ii7PPmJVrxk1ptxt3QRbNxCX3Ks/UZ5sawnLDzWcFNSjjmxbZ3q4+gmss9j+FjnOVhSs3W+4V5SuJ0t74XBea/UnoCMlGMh1nuTOCqoyVnOFJmmrg/7D8jFIGVchlf/p/9k2Jdl8itPB3+tUTW+YNqGBKWdCTf+xGXVdXVIhQSHs8sBSCnNRDWo/CNOuLcsHKWFJaq27Mgppy1hfFuxSYeEsv8hNYDA6b5G3Yq6W/CzJH0rcL3aUpf18bW5DPn6zUNd+Fw1ddHi3tH68T+kLOtd5Q0zEFif7TjsQ807FYcaNAxB5vQTzM4dkesWqyjmdIFIinOEiEjqhdnRpPBh+2V6P78rdirFS4eCG5Edve9Tfyb8Joj6VtF19E1wWlU/AES9bATkETlXcNxMiBBg3JbLJrqWSCw+gi1/Zg5mac/PRHuZK/Pyn9T9RTGYoNbheYSI03H/LlI0L+w1Z2TnKVciZErDYC6d2fWvpEd0qh/pjB1A5po5Xs6dTcTmLFUaieWLhNLS9N9Q7ZsoWZk5V41jtOCzD9oYrF/oU88AdaeETLkQkIhcZsUHRekA+5bL+5qizx2anRA/p17UTflXUQ4WhgzKC8nl8vvDZJkSDAKIPte8+rw27cbvuUJLIO8HU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
